### ISSUE TITLE
无法提取知网数据且在其他网站无反应1124

### ISSUE THREAD

**Issue by Dengling82465** [l0o0/jasminum#228]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：6.0.26
**Jasminum 插件版本**：0.2.8

**其他功能异常**

请详细说明操作步骤，出现的错误提示信息等
无法抓取知网数据，如图所示而且在在如pubscholar、读秀等不可用

**Comment by Dengling82465** [comment]
![屏幕截图 2023-11-24 194046](https://github.com/l0o0/jasminum/assets/148857609/e35ef4c3-f011-4de0-b556-7ed9c58cb401)
补充截图

**Comment by northword** [comment]
图示题录信息已提取成功。

只要条目可以正常保存就视为成功的抓取，PDF 附件影响因素过多，无法成功获取 PDF 时请手动下载。

**Comment by Dengling82465** [comment]
> 图示题录信息已提取成功。
> 
> 只要条目可以正常保存就视为成功的抓取，PDF 附件影响因素过多，无法成功获取 PDF 时请手动下载。

您好！也有这种情况，并没有成功抓取
![image](https://github.com/l0o0/jasminum/assets/148857609/b0c11b1e-c5ca-4252-9f0c-55f7ea033dc5)

**Comment by Dengling82465** [comment]
![image](https://github.com/l0o0/jasminum/assets/148857609/b4ba5f0e-64d3-4dff-beff-bf9eb1fa8496)
补充：还会出现识别错误的问题

**Comment by Dengling82465** [comment]
补充：还会出现这种什么也不出现的问题
![image](https://github.com/l0o0/jasminum/assets/148857609/9517f64f-34ce-475a-ab91-e8f5a749d0ca)

**Comment by s4721525101** [comment]
也是这种情况
![image](https://github.com/l0o0/jasminum/assets/151977278/f8e1a066-f83f-4104-9df0-c8c6b52c139f)

**Comment by l0o0** [comment]
@Dengling82465 @s4721525101 是不是使用学校vpn之类的登录知网？

**Comment by s4721525101** [comment]
> @Dengling82465 @s4721525101 是不是使用学校vpn之类的登录知网？

是的，但是后面没连vpn，校外登录知网，也还是不行。。。

**Comment by l0o0** [comment]
> 是的，但是后面没连vpn，校外登录知网，也还是不行。。。

好的，后面我再想办法更新

**Comment by oafoak** [comment]
[JavaScript Error: "Error: HTTP request to https://kns.cnki.net/dm/api/ShowExport rejected with status 404
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/messaging_inject.js:79:17
    at async Zotero.Utilities.Translate.request (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translate/utilities_translate.js:320:12)
    at async getRefWorksByID (eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/sandboxManager.js:63:4), <anonymous>:41:16)
    at async scrape (eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/sandboxManager.js:63:4), <anonymous>:243:16)
    at async doWeb (eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/sandboxManager.js:63:4), <anonymous>:238:3)" {file: "[object Object]"}]

**Comment by oafoak** [comment]
![image](https://github.com/l0o0/jasminum/assets/59524337/b6cfbd7f-3dc8-4b41-8ad3-1b65f1231d4d)

**Comment by jiaojiaodubai** [comment]
知网转换器已经跟进2023年11月底的更新，现在应该无此问题了

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
